"""
forge.promote

Write the current champion prompts back into Valinor's codexHarness.ts so the
real harness uses the tuned prompts.

This edits a DIFFERENT repository (../valinor) — a hard-to-reverse, outward
action — so it is **dry-run by default**. Review the plan, then re-run with
`--apply` to actually write.

How it wires in (safe + reversible):
  1. Writes the three champion prompts to a generated TS module
     `valinor/src/runtime/agents/forgePrompts.generated.ts`.
  2. Replaces the `ROLE_INSTRUCTIONS` const in codexHarness.ts to consume that
     module (one import + one anchored block replace). Idempotent — re-running
     just refreshes the generated file.
  3. Saves an out-of-tree copy of the original codexHarness.ts under
     state/promote-backups/. The edit is git-tracked in Valinor, so a full
     revert is `git -C ../valinor checkout -- <files>`.

The champion prompt already contains the full role instruction (base + shared
rules), so we REPLACE the assembled ROLE_INSTRUCTIONS rather than the
BASE_ROLE_INSTRUCTIONS pieces — no rule double-append.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

from .config import CONFIG, ROLES
from .experiment import ChampionPrompts


_GENERATED_NAME = "forgePrompts.generated.ts"
_ANCHOR = "const ROLE_INSTRUCTIONS: Record<AgentRole, string> = {"
_IMPORT = 'import { FORGE_ROLE_INSTRUCTIONS } from "./forgePrompts.generated";'
_WIRE = (
    "// [forge-promote] ROLE_INSTRUCTIONS sourced from tuned champion prompts.\n"
    "const ROLE_INSTRUCTIONS: Record<AgentRole, string> = "
    "FORGE_ROLE_INSTRUCTIONS as Record<AgentRole, string>;"
)


def _ts_literal(s: str) -> str:
    """Escape a Python string for embedding in a TS backtick template literal."""
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def _generated_module(champion: ChampionPrompts) -> str:
    parts = [
        "// AUTO-GENERATED by `forge promote` — do not edit by hand.",
        "// Source: valinor-prompt-forge champion prompts.",
        f"// Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "export const FORGE_ROLE_INSTRUCTIONS: Record<string, string> = {",
    ]
    for role in ROLES:
        parts.append(f"  {role}: `{_ts_literal(champion.for_role(role))}`,")
    parts.append("};")
    parts.append("")
    return "\n".join(parts)


def _find_block_end(text: str, start: int) -> int:
    """Index just past the `};` that closes the object opened at `start`."""
    close = text.find("\n};", start)
    if close < 0:
        return -1
    return close + len("\n};")


def promote(apply: bool) -> int:
    champ_dir = CONFIG.prompts_champion_dir
    if not all((champ_dir / f"{r}.md").exists() for r in ROLES):
        print(f"[forge] no champion prompts in {champ_dir}. Run `forge run` first.", file=sys.stderr)
        return 2
    champion = ChampionPrompts.load(champ_dir)

    harness = CONFIG.valinor_harness_file
    if not harness.exists():
        print(f"[forge] Valinor harness not found at {harness}.", file=sys.stderr)
        print("        Set the path in forge/config.py (valinor_harness_file).", file=sys.stderr)
        return 2

    src = harness.read_text(encoding="utf-8")
    gen_path = harness.parent / _GENERATED_NAME
    already_wired = "FORGE_ROLE_INSTRUCTIONS" in src

    # ── compute the planned codexHarness.ts edit
    new_src = src
    edit_desc: list[str] = []

    if _IMPORT not in new_src:
        # Insert the import after the last existing top-of-file import line.
        lines = new_src.splitlines(keepends=True)
        last_import = 0
        for i, ln in enumerate(lines):
            if ln.startswith("import "):
                last_import = i + 1
        lines.insert(last_import, _IMPORT + "\n")
        new_src = "".join(lines)
        edit_desc.append("add import of forgePrompts.generated")

    if not already_wired:
        anchor = new_src.find(_ANCHOR)
        if anchor < 0:
            print("[forge] could not find the ROLE_INSTRUCTIONS anchor in codexHarness.ts.",
                  file=sys.stderr)
            print(f"        Expected: {_ANCHOR!r}", file=sys.stderr)
            print("        Aborting rather than risk corrupting the file.", file=sys.stderr)
            return 2
        end = _find_block_end(new_src, anchor)
        if end < 0:
            print("[forge] found the anchor but not its closing `};`. Aborting.", file=sys.stderr)
            return 2
        new_src = new_src[:anchor] + _WIRE + new_src[end:]
        edit_desc.append("replace ROLE_INSTRUCTIONS const with FORGE_ROLE_INSTRUCTIONS")
    else:
        edit_desc.append("already wired — refresh generated prompts only")

    # ── report
    print(f"[forge] champion: {champ_dir}")
    print(f"[forge] target  : {harness}")
    print(f"[forge] generate: {gen_path}")
    for d in edit_desc:
        print(f"[forge]   - {d}")
    for role in ROLES:
        print(f"[forge]   {role} prompt: {len(champion.for_role(role))} chars")

    if not apply:
        print("\n[forge] DRY RUN — nothing written. Re-run `forge promote --apply` to write.")
        return 0

    # ── apply: out-of-tree backup, then write
    backups = CONFIG.state_dir / "promote-backups"
    backups.mkdir(parents=True, exist_ok=True)
    bak = backups / f"codexHarness.{time.strftime('%Y%m%d-%H%M%S')}.ts"
    bak.write_text(src, encoding="utf-8")
    print(f"[forge] backup  : {bak}")

    gen_path.write_text(_generated_module(champion), encoding="utf-8")
    if new_src != src:
        harness.write_text(new_src, encoding="utf-8")

    print("[forge] promoted. Rebuild Valinor to pick up the new prompts.")
    print(f"[forge] revert with: git -C \"{CONFIG.valinor_repo}\" checkout -- "
          f"src/runtime/agents/codexHarness.ts && del \"{gen_path}\"")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    return promote(apply="--apply" in argv)


if __name__ == "__main__":
    raise SystemExit(main())
